# Change these first
owner: BrikerMan
repo: uptimes

# Add your sites here
sites:
  - name: MAS SDK New
    url: https://global-sdk-test.mas.yodo1.com/api/info
  - name: MAS SDK Development
    url: https://sdk.mas.yodo1.me/api/health_check
  - name: MAS SDK Production
    url: https://sdk.mas.yodo1.com/v1/init/jMQ9rTKQDuF?country=AU

status-website:
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptimes
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
